name: Lint with Pylint

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python with uv
        uses: drivendataorg/setup-python-uv-action@v2
        with:
          python-version: '3.x'
          cache: 'packages'

      - name: Install dependencies
        run: |
          uv sync

      - name: Run Pylint
        run: |
          uv run pylint --version
          uv run pylint **/*.py
